# --- サイト基本設定 ---
title: インテイク非公式information
author: piencode
description: "インテイクの非公式情報サイトです。"
baseurl: "/intake_information"
url: "https://piencode.github.io"

# --- Jekyll コレクション設定 ---
collections:
  news:
    output: true
    sort_by: date
  main_lives: # ← main_lives の設定があるか
    output: true

# --- Jekyll プラグイン設定 ---
plugins:
  - jekyll-paginate-v2

# --- ページネーション設定 (これは news.html のために残します) ---
pagination:
  enabled: true
  per_page: 10
  collection: "news"
  sort_field: "date"
  sort_reverse: true
  permalink: "/news/page/:num/"
# autopages: のブロックは、このファイルから完全に削除する

# --- 日付が変わったことの判定を東京基準で行う　--- #
timezone: Asia/Tokyo
