duo:
  name: "インテイク"
  image: "int_image_02.JPG"
  description: |
    NSC東京23期。
    吉本興業所属の芸歴8年目。

    [成績]
    M-1グランプリ2022  準々決勝進出
    ツギクル芸人グランプリ2023 決勝進出
    M-1グランプリ2024 準々決勝進出
  links:
    - name: "公式サイト"
      url: "https://profile.yoshimoto.co.jp/talent/detail?id=8976"
      icon: "fa-solid fa-globe"
    - name: "インテイクのカド"
      url: "https://stand.fm/channels/6030fcec85b142d0d89e72df"
      icon: "fa-solid fa-podcast"
    - name: "Wiki"
      url: "https://ja.everybodywiki.com/%E3%82%A4%E3%83%B3%E3%83%86%E3%82%A4%E3%82%AF_(%E3%81%8A%E7%AC%91%E3%81%84)"
      icon: "fa-brands fa-wikipedia-w"

members:
  - name: "鈴木龍平"
    image: "suzuki_02.jpg"
    bio: |
      1996年1月31日うまれ。
      埼玉県川口市出身。
      インテイクのネタ作成＆ボケ担当。
    social:
      twitter: "https://twitter.com/Ryu_su_131"
      instagram: "https://instagram.com/intk__7"
    group:
      bio: |
        【 崎食あそ美 】
        鈴木さん、マリーマリー・タコスさん、おとうふ・山中さんのほのぼのYouTubeチャンネル
      social:
        instagram: "https://instagram.com/asomi_sakitabe"
        youtube: "https://youtube.com/@sakitabe"

  - name: "まえかず"
    image: "maekz_02.jpg"
    bio: |
      1993年12月22日うまれ。
      青森県おいらせ町出身。
      インテイクのツッコミ(リアクション)担当。
    social:
      twitter: "https://twitter.com/intmaekz"
      instagram: "https://instagram.com/int_maekz"
      threads: "https://threads.net/int_maekz"
      youtube: "https://youtube.com/@int_maekz1222"
